site_name: itd-sdk
site_url: https://itdsdk.qzz.io/docs/
repo_url: https://github.com/firedotguy/itd-sdk

theme:
  name: material
  features:
    - navigation.footer
    - content.code.annotate

  palette:
    scheme: slate
    primary: deep orange
    accent: orange

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

extra_css:
  - stylesheets/extra.css

nav:
  - index.md
  - launch.md
  - base_errors.md
  - Методы:
    - methods/posts.md
    - methods/auth.md
    - methods/users.md
  - API Reference:
    - api/client.md
    - Models:
      - api/models/post.md
      - api/models/comment.md
      - api/models/user.md
      - api/models/clan.md
      - api/models/hashtag.md
      - api/models/notification.md
      - api/models/file.md
      - api/models/pagination.md
      - api/models/report.md
      - api/models/event.md
      - api/models/pin.md
      - api/models/verification.md
    - api/enums.md
    - api/utils.md

# часть кофига взята из aioitd
plugins:
    - mkdocstrings:
        handlers:
          python:
            paths: [itd]
            options:
              extensions:
                - griffe_typingdoc
              docstring_style: google
              show_source: false
              separate_signature: true
              filters:
                - '!^_'
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              show_root_heading: true
              show_signature_annotations: true
              signature_crossrefs: true
              show_labels: false
              show_if_no_docstring: true
              inherited_members: true
              unwrap_annotated: true
