[build-system]
requires = ["uv_build~=0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = 'itd'
module-root = ''

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version_provider = "uv"

[project]
name = "itd-sdk"
version = "2.9.1"
description = "ITD client for python"
readme = "README.md"
authors = [
  { name = "fi-res", email = "nta16022013@gmail.com" }
]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Natural Language :: Russian',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Framework :: Pydantic :: 2'
]
keywords = ['itd', 'itdsocial']
license = "MIT"
dependencies = [
  "requests>=2.32.5,<2.35.0",
  "pydantic>=2.12.5,<2.14.0",
  "sseclient-py~=1.9.0",
  "telegramify-markdown>=0.5.4",
  "lxml>=6.1.1",
  "platformdirs>=4.10.0",
  # "websockets>=16.1.1",
]
requires-python = ">=3.10"

[project.urls]
Homepage = 'https://itdsdk.qzz.io'
Documentation = 'https://itdsdk.qzz.io/docs'

[project.optional-dependencies]
filetype = [
    "filetype>=1.2.0",
]
logs = [
    "rich>=15.0.0",
]
date = [
    "dateparser>=1.2.2",
]
qrcode = [
    "qrcode>=8.2",
]
captcha = [
    "camoufox[geoip]>=0.4.11",
    "playwright>=1.62.0"
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "python-dotenv>=1.2.1",
]

[project.scripts]
itd-sdk = "itd.core.cli:main"

[tool.ruff]
line-length = 160

[tool.ruff.lint]
ignore = ["COM", "D300", "E501", 'E741', 'E731']

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true
